apiVersion: v1
kind: Service
metadata:
  name: {{ include "key-manager-grpc.fullname" . }}-external-apps-svc
  labels:
    {{- include "key-manager-grpc.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 3306
      protocol: TCP
      name: db
    - port: 9091
      protocol: TCP
      name: erp
    - port: 8082
      protocol: TCP
      name: bcb
  selector:
    {{- include "key-manager-grpc.selectorLabels" . | nindent 4 }}-external-app
