apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "key-manager-grpc.fullname" . }}-configmap
data:
  MYSQL_HOST: {{ .Values.env.grpc.mysql.host | quote }}
  MYSQL_PORT: {{ .Values.env.grpc.mysql.port | quote }}
  MYSQL_USER: {{ .Values.env.grpc.mysql.user | quote }}
  BCB_HOST: {{ .Values.env.grpc.bcb.host | quote }}
  BCB_PORT: {{ .Values.env.grpc.bcb.port | quote }}
  ERP_HOST: {{ .Values.env.grpc.erp.host | quote }}
  ERP_PORT: {{ .Values.env.grpc.erp.port | quote }}
